# Generated by Django 3.1.2 on 2020-10-23 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('orderId', models.CharField(max_length=200, verbose_name='Order Id')),
                ('razorpay_id', models.CharField(max_length=250, verbose_name='Razorpay Id')),
                ('paymentStatus', models.BooleanField(default=False, verbose_name='Payment status')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('publishDate', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryType', models.CharField(choices=[('Mobiles', 'Mobiles'), ('Laptops', 'Laptops'), ('Led', 'Led'), ('Books', 'Books'), ('Toys', 'Toys'), ('Accessories', 'Accessories')], default='-', max_length=40)),
                ('productName', models.CharField(help_text='Please enter product name', max_length=80)),
                ('productDetails', models.TextField(help_text='Please enter details', max_length=500)),
                ('productPrice', models.PositiveIntegerField(help_text='Please enter a price, in Rupees')),
                ('productImage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='userShippingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedDate', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='Buyer Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('city', models.CharField(choices=[('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Mumbai', 'Mumbai'), ('Banglore', 'Banglore'), ('Delhi', 'Delhi'), ('Rewa', 'Rewa')], max_length=20, verbose_name='Buyer City')),
                ('pincode', models.PositiveIntegerField(verbose_name='Buyer city code')),
                ('country', models.CharField(choices=[('India', 'India')], max_length=10, verbose_name='Buyer Country')),
                ('address', models.TextField(max_length=300, verbose_name='Buyer Full Address')),
                ('mobile', models.PositiveIntegerField(verbose_name='Buyer Number')),
                ('product', models.JSONField(verbose_name='Product In JSON type')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderstatus', verbose_name='Order Id')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('ProfilePicture', models.ImageField(blank=True, null=True, upload_to='userProfile/%Y/%m/%d/')),
                ('pinCode', models.PositiveIntegerField(blank=True, help_text='Enter your area pincode!', null=True)),
                ('address', models.CharField(help_text='Enter vaild address.', max_length=100)),
                ('officeAddress', models.CharField(blank=True, help_text='enter your office address!..', max_length=100, null=True)),
                ('mobile', models.PositiveIntegerField(help_text='Enter valid number.')),
                ('alternateMobile', models.PositiveIntegerField(blank=True, help_text='Enter your second number! in case your first nuber switchoff, we contact through this number', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
