# Generated by Django 3.1.2 on 2020-10-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingdetail',
            name='orderId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.orderstatus', verbose_name='Order Id'),
        ),
    ]
