# Generated by Django 3.1.2 on 2020-10-29 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201025_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='trackOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage1', models.CharField(max_length=200, verbose_name='stage 1')),
                ('stage2', models.CharField(max_length=200, verbose_name='stage 2')),
                ('stage3', models.CharField(max_length=200, verbose_name='stage 3')),
                ('stage4', models.CharField(max_length=200, verbose_name='stage 6')),
                ('stage5', models.CharField(max_length=200, verbose_name='stage 7')),
                ('delivery', models.DateField(verbose_name='Enter excepted date')),
                ('orderReceived', models.BooleanField(verbose_name='Order received')),
                ('orderReceivedDate', models.DateField(verbose_name='After receiving date')),
                ('orderId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.orderstatus')),
            ],
        ),
    ]
